import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./global-icons.css";
import NavMenu from "@/components/nav-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-light-grey">
      <body className={`${inter.className} px-2 sm:px-10 md:px-16 lg:px-48`}>
        <NavMenu/>
        <div className="max-w-screen-xl mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}