using Microsoft.AspNetCore.Identity;
using Swapsha.Api.Features.Users.Models;

namespace Swapsha.Api.Features.Users;

public class UserSeed
{
    public static List<CustomUser> Seed()
    {
        var passwordHasher = new PasswordHasher<CustomUser>();

        var users = new List<CustomUser>
        {
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Adam",
                LastName = "Larsson",
                MiddleName = "Karl",
                ProfilePictureUrl = null,
                UserName = "test1@example.com",
                NormalizedUserName = "TEST1@EXAMPLE.COM",
                Email = "test1@example.com",
                NormalizedEmail = "TEST1@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Adrian",
                LastName = "Bodin",
                MiddleName = "Nils",
                ProfilePictureUrl = null,
                UserName = "test2@example.com",
                NormalizedUserName = "TEST2@EXAMPLE.COM",
                Email = "test2@example.com",
                NormalizedEmail = "TEST2@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Fredrik",
                LastName = "Andersson",
                MiddleName = "Johan",
                ProfilePictureUrl = null,
                UserName = "test3@example.com",
                NormalizedUserName = "TEST3@EXAMPLE.COM",
                Email = "test3@example.com",
                NormalizedEmail = "TEST3@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Lisa",
                LastName = "Andersson",
                MiddleName = "Caroline",
                ProfilePictureUrl = null,
                UserName = "test4@example.com",
                NormalizedUserName = "TEST4@EXAMPLE.COM",
                Email = "test4@example.com",
                NormalizedEmail = "TEST4@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Emma",
                LastName = "Johansson",
                MiddleName = "Sofia",
                ProfilePictureUrl = null,
                UserName = "test5@example.com",
                NormalizedUserName = "TEST5@EXAMPLE.COM",
                Email = "test5@example.com",
                NormalizedEmail = "TEST5@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "John",
                LastName = "Doe",
                MiddleName = "Robert",
                ProfilePictureUrl = null,
                UserName = "test6@example.com",
                NormalizedUserName = "TEST6@EXAMPLE.COM",
                Email = "test6@example.com",
                NormalizedEmail = "TEST6@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Alice",
                LastName = "Smith",
                MiddleName = "Grace",
                ProfilePictureUrl = null,
                UserName = "test7@example.com",
                NormalizedUserName = "TEST7@EXAMPLE.COM",
                Email = "test7@example.com",
                NormalizedEmail = "TEST7@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Michael",
                LastName = "Johnson",
                MiddleName = "David",
                ProfilePictureUrl = null,
                UserName = "test8@example.com",
                NormalizedUserName = "TEST8@EXAMPLE.COM",
                Email = "test8@example.com",
                NormalizedEmail = "TEST8@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Emily",
                LastName = "Brown",
                MiddleName = "Anne",
                ProfilePictureUrl = null,
                UserName = "test9@example.com",
                NormalizedUserName = "TEST9@EXAMPLE.COM",
                Email = "test9@example.com",
                NormalizedEmail = "TEST9@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "David",
                LastName = "Wilson",
                MiddleName = "Paul",
                ProfilePictureUrl = null,
                UserName = "test10@example.com",
                NormalizedUserName = "TEST10@EXAMPLE.COM",
                Email = "test10@example.com",
                NormalizedEmail = "TEST10@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Sarah",
                LastName = "Martinez",
                MiddleName = "Jane",
                ProfilePictureUrl = null,
                UserName = "test11@example.com",
                NormalizedUserName = "TEST11@EXAMPLE.COM",
                Email = "test11@example.com",
                NormalizedEmail = "TEST11@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Daniel",
                LastName = "Garcia",
                MiddleName = "Carlos",
                ProfilePictureUrl = null,
                UserName = "test12@example.com",
                NormalizedUserName = "TEST12@EXAMPLE.COM",
                Email = "test12@example.com",
                NormalizedEmail = "TEST12@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Olivia",
                LastName = "Rodriguez",
                MiddleName = "Maria",
                ProfilePictureUrl = null,
                UserName = "test13@example.com",
                NormalizedUserName = "TEST13@EXAMPLE.COM",
                Email = "test13@example.com",
                NormalizedEmail = "TEST13@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "William",
                LastName = "Lopez",
                MiddleName = "Alexander",
                ProfilePictureUrl = null,
                UserName = "test14@example.com",
                NormalizedUserName = "TEST14@EXAMPLE.COM",
                Email = "test14@example.com",
                NormalizedEmail = "TEST14@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Ethan",
                LastName = "Gonzalez",
                MiddleName = "Gabriel",
                ProfilePictureUrl = null,
                UserName = "test15@example.com",
                NormalizedUserName = "TEST15@EXAMPLE.COM",
                Email = "test15@example.com",
                NormalizedEmail = "TEST15@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "James",
                LastName = "Hernandez",
                MiddleName = "Andrew",
                ProfilePictureUrl = null,
                UserName = "test16@example.com",
                NormalizedUserName = "TEST16@EXAMPLE.COM",
                Email = "test16@example.com",
                NormalizedEmail = "TEST16@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Benjamin",
                LastName = "Perez",
                MiddleName = "Joseph",
                ProfilePictureUrl = null,
                UserName = "test17@example.com",
                NormalizedUserName = "TEST17@EXAMPLE.COM",
                Email = "test17@example.com",
                NormalizedEmail = "TEST17@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Sophia",
                LastName = "Ramirez",
                MiddleName = "Isabella",
                ProfilePictureUrl = null,
                UserName = "test18@example.com",
                NormalizedUserName = "TEST18@EXAMPLE.COM",
                Email = "test18@example.com",
                NormalizedEmail = "TEST18@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Mia",
                LastName = "Gomez",
                MiddleName = "Sophia",
                ProfilePictureUrl = null,
                UserName = "test19@example.com",
                NormalizedUserName = "TEST19@EXAMPLE.COM",
                Email = "test19@example.com",
                NormalizedEmail = "TEST19@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            }
        };

        return users;
    }
}