using Microsoft.AspNetCore.Identity;
using Swapsha.Api.Features.Users.Models;

namespace Swapsha.Api.Features.Users.Seed;

public class UserSeed
{
    public static List<CustomUser> Seed()
    {
        var passwordHasher = new PasswordHasher<CustomUser>();

        var users = new List<CustomUser>
        {
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Adam",
                LastName = "Larsson",
                MiddleName = "Karl",
                CityId = 2,
                //write a more generic bio
                Bio = "I'm Adam, a cheerful individual with a passion for helping others. My expertise lies in gardening and I'm seeking assistance with bricklaying projects.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser1/profilepic.jpg",
                UserName = "test1@example.com",
                NormalizedUserName = "TEST1@EXAMPLE.COM",
                Email = "test1@example.com",
                NormalizedEmail = "TEST1@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Adrian",
                LastName = "Bodin",
                CityId = 5,
                Bio = "Hello, I'm Adrian. I'm a professional with a diverse skill set, always ready to learn and take on new challenges.",
                MiddleName = "Nils",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser2/profilepic.jpg",
                UserName = "test2@example.com",
                NormalizedUserName = "TEST2@EXAMPLE.COM",
                Email = "test2@example.com",
                NormalizedEmail = "TEST2@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Fredrik",
                LastName = "Andersson",
                MiddleName = "Johan",
                CityId = 8,
                Bio = "I'm Fredrik, a dedicated and hardworking individual. I enjoy problem-solving and always strive for excellence in everything I do.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser3/profilepic.jpg",
                UserName = "test3@example.com",
                NormalizedUserName = "TEST3@EXAMPLE.COM",
                Email = "test3@example.com",
                NormalizedEmail = "TEST3@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Lisa",
                LastName = "Andersson",
                MiddleName = "Caroline",
                CityId = 8,
                Bio = "Hi, I'm Lisa. I'm passionate about continuous learning and improvement. I believe in the power of positivity and hard work.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser4/profilepic.jpg",
                UserName = "test4@example.com",
                NormalizedUserName = "TEST4@EXAMPLE.COM",
                Email = "test4@example.com",
                NormalizedEmail = "TEST4@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Emma",
                LastName = "Johansson",
                MiddleName = "Sofia",
                CityId = 1,
                Bio = "I'm Emma, a creative thinker with a knack for finding innovative solutions. I love to explore new ideas and concepts.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser5/profilepic.jpg",
                UserName = "test5@example.com",
                NormalizedUserName = "TEST5@EXAMPLE.COM",
                Email = "test5@example.com",
                NormalizedEmail = "TEST5@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "John",
                LastName = "Doe",
                MiddleName = "Robert",
                CityId = 11,
                Bio = "Hello, I'm John. I'm a highly motivated individual with a strong work ethic. I'm always ready to take on new challenges and learn new skills.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser6/profilepic.jpg",
                UserName = "test6@example.com",
                NormalizedUserName = "TEST6@EXAMPLE.COM",
                Email = "test6@example.com",
                NormalizedEmail = "TEST6@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Alice",
                LastName = "Smith",
                MiddleName = "Grace",
                CityId = 10,
                Bio = "Hi, I'm Alice. I'm a detail-oriented professional who takes pride in producing high-quality work. I'm always eager to learn and grow professionally.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser7/profilepic.jpg",
                UserName = "test7@example.com",
                NormalizedUserName = "TEST7@EXAMPLE.COM",
                Email = "test7@example.com",
                NormalizedEmail = "TEST7@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Michael",
                LastName = "Johnson",
                MiddleName = "David",
                CityId = 9,
                Bio = "I'm Michael, a dedicated professional with a passion for learning. I'm always looking for opportunities to expand my skill set and contribute to a team.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser8/profilepic.jpg",
                UserName = "test8@example.com",
                NormalizedUserName = "TEST8@EXAMPLE.COM",
                Email = "test8@example.com",
                NormalizedEmail = "TEST8@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Emily",
                LastName = "Brown",
                MiddleName = "Anne",
                CityId = 7,
                Bio = "Hello, I'm Emily. I'm a proactive individual with a passion for learning and growth. I'm always looking for ways to improve and take on new challenges.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser9/profilepic.jpg",
                UserName = "test9@example.com",
                NormalizedUserName = "TEST9@EXAMPLE.COM",
                Email = "test9@example.com",
                NormalizedEmail = "TEST9@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "David",
                LastName = "Wilson",
                MiddleName = "Paul",
                CityId = 13,
                Bio = "I'm David, a hardworking professional with a passion for excellence. I'm always ready to take on new challenges and learn new skills.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser10/profilepic.jpg",
                UserName = "test10@example.com",
                NormalizedUserName = "TEST10@EXAMPLE.COM",
                Email = "test10@example.com",
                NormalizedEmail = "TEST10@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Sarah",
                LastName = "Martinez",
                MiddleName = "Jane",
                CityId = 12,
                Bio = "Hi, I'm Sarah. I'm a dedicated professional with a passion for learning. I'm always looking for opportunities to expand my skill set and contribute to a team.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser11/profilepic.jpg",
                UserName = "test11@example.com",
                NormalizedUserName = "TEST11@EXAMPLE.COM",
                Email = "test11@example.com",
                NormalizedEmail = "TEST11@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Daniel",
                LastName = "Garcia",
                MiddleName = "Carlos",
                CityId = 14,
                Bio = "I'm Daniel, a motivated individual with a strong work ethic. I'm always ready to take on new challenges and learn new skills.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser12/profilepic.jpg",
                UserName = "test12@example.com",
                NormalizedUserName = "TEST12@EXAMPLE.COM",
                Email = "test12@example.com",
                NormalizedEmail = "TEST12@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Olivia",
                LastName = "Rodriguez",
                MiddleName = "Maria",
                CityId = 15,
                Bio = "Hello, I'm Olivia. I'm a detail-oriented professional who takes pride in producing high-quality work. I'm always eager to learn and grow professionally.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser13/profilepic.jpg",
                UserName = "test13@example.com",
                NormalizedUserName = "TEST13@EXAMPLE.COM",
                Email = "test13@example.com",
                NormalizedEmail = "TEST13@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "William",
                LastName = "Lopez",
                MiddleName = "Alexander",
                CityId = 16,
                Bio = "I'm William, a dedicated professional with a passion for learning. I'm always looking for opportunities to expand my skill set and contribute to a team.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser14/profilepic.jpg",
                UserName = "test14@example.com",
                NormalizedUserName = "TEST14@EXAMPLE.COM",
                Email = "test14@example.com",
                NormalizedEmail = "TEST14@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Ethan",
                LastName = "Gonzalez",
                MiddleName = "Gabriel",
                CityId = 5,
                Bio = "Hi, I'm Ethan. I'm a proactive individual with a passion for learning and growth. I'm always looking for ways to improve and take on new challenges.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser15/profilepic.jpg",
                UserName = "test15@example.com",
                NormalizedUserName = "TEST15@EXAMPLE.COM",
                Email = "test15@example.com",
                NormalizedEmail = "TEST15@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "James",
                LastName = "Hernandez",
                MiddleName = "Andrew",
                CityId = 3,
                Bio = "I'm James, a hardworking professional with a passion for excellence. I'm always ready to take on new challenges and learn new skills.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser16/profilepic.jpg",
                UserName = "test16@example.com",
                NormalizedUserName = "TEST16@EXAMPLE.COM",
                Email = "test16@example.com",
                NormalizedEmail = "TEST16@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Benjamin",
                LastName = "Perez",
                MiddleName = "Joseph",
                CityId = 1,
                Bio = "Hello, I'm Benjamin. I'm a motivated individual with a strong work ethic. I'm always ready to take on new challenges and learn new skills.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser17/profilepic.jpg",
                UserName = "test17@example.com",
                NormalizedUserName = "TEST17@EXAMPLE.COM",
                Email = "test17@example.com",
                NormalizedEmail = "TEST17@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Sophia",
                LastName = "Ramirez",
                MiddleName = "Isabella",
                CityId = 9,
                Bio = "I'm Sophia, a detail-oriented professional who takes pride in producing high-quality work. I'm always eager to learn and grow professionally.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser18/profilepic.jpg",
                UserName = "test18@example.com",
                NormalizedUserName = "TEST18@EXAMPLE.COM",
                Email = "test18@example.com",
                NormalizedEmail = "TEST18@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            },
            new CustomUser
            {
                Id = Guid.NewGuid().ToString(),
                FirstName = "Mia",
                LastName = "Gomez",
                MiddleName = "Sophia",
                CityId = 11,
                Bio = "Hi, I'm Mia. I'm a dedicated professional with a passion for learning. I'm always looking for opportunities to expand my skill set and contribute to a team.",
                ProfilePictureUrl = "https://swapshastorage.blob.core.windows.net/seeduser19/profilepic.jpg",
                UserName = "test19@example.com",
                NormalizedUserName = "TEST19@EXAMPLE.COM",
                Email = "test19@example.com",
                NormalizedEmail = "TEST19@EXAMPLE.COM",
                EmailConfirmed = false,
                SecurityStamp = Guid.NewGuid().ToString(),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                PhoneNumber = null,
                PhoneNumberConfirmed = false,
                TwoFactorEnabled = false,
                LockoutEnd = null,
                LockoutEnabled = true,
                AccessFailedCount = 0,
                PasswordHash = passwordHasher.HashPassword(null, "Admin123!")
            }
        };

        return users;
    }
}